services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # Verifica se o banco de dados esta pronto para aceitar conexões
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  my-app:
    build: .
    container_name: my-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/uploads
    # Espera o banco de dados estar pronto para se conectar
    depends_on:
      postgres-db:
        condition: service_healthy
volumes:
  postgres_data: