cors:
  originPatterns: http://localhost:8080, http://localhost:3000
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}?useTimezone=true&serverTimezone=UTC
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    root: info
spring-doc:
  paths-to-match: /api/v1/**/**
  swagger-ui:
    use-root-path: true