cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /uploads
email:
  subject: "Default subject"
  message: "Default message"
security:
  jwt:
    secret-key: "${JWT_SECRET_KEY}"
    expiration: "${JWT_EXPIRATION_MS:3600000}" # 1 hora
  password:
    encoder:
      secret: "${PASSWORD_ENCODER_SECRET}"
      iterations: "${PASSWORD_ENCODER_ITERATIONS:185000}" # 185.000 iterações
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}?useTimezone=true&serverTimezone=UTC
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB
logging:
  level:
    root: info
spring-doc:
  paths-to-match:
    - /auth/**
    - /api/v1/**/**
  swagger-ui:
    use-root-path: true