spring:
  datasource:
    url: "${URL_DB}"
    username: "${USERNAME_DB}"
    password: "${PASSWORD_DB}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    root: info
spring-doc:
  paths-to-match: /api/v1/**/**
  swagger-ui:
    use-root-path: true