spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyAppDB?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    root: warn