CREATE TABLE public.tb_person
(
    id         bigint                 NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name  character varying(100) NOT NULL,
    cpf        character varying(100) NOT NULL,
    gender     character varying(6)   NOT NULL,
    CONSTRAINT tb_person_gender_check CHECK (((gender)::text = ANY
                                              ((ARRAY ['M'::character varying, 'F'::character varying])::text[])))
);

-- Define o proprietário da tabela para 'postgres'
ALTER TABLE public.tb_person
    OWNER TO postgres;

-- Configuração da coluna 'id' como IDENTITY
-- Isso cria automaticamente a sequência 'public.tb_person_id_seq' e a vincula à coluna 'id'.
-- O valor inicial da sequência será 1 por padrão, pois não há inserções de dados aqui.
ALTER TABLE public.tb_person
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.tb_person_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

-- Garante que o CPF seja único na tabela
ALTER TABLE ONLY public.tb_person
    ADD CONSTRAINT tb_person_cpf_key UNIQUE (cpf);

-- Define a chave primária da tabela
ALTER TABLE ONLY public.tb_person
    ADD CONSTRAINT tb_person_pkey PRIMARY KEY (id);

