name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código. Baixa o código do repositório para a máquina virtual.
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configura a versão do Java 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Passo 3: Cache de dependências do Maven. Guarda as dependências baixadas para acelerar builds futuros.
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Passo 4: Rodar Build e Testes com Maven
      - name: Build and run tests with Maven
        run: mvn -B clean install --file pom.xml
